name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    name: build

    steps:
      - uses: actions/setup-java@v4
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: "21"

      - uses: actions/checkout@v4
        name: checkout
        with:
          repository: MikeEdgar/smallrye-open-api
          ref: main
          path: smallrye-open-api

      - name: build smallrye-open-api
        run: mvn -B -f smallrye-open-api/pom.xml install -pl extension-jaxrs -am -DskipTests

      - uses: actions/checkout@v4
        name: checkout
        with:
          path: reproducer

      - name: build with maven
        run: mvn -B -f reproducer/pom.xml package
