name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    name: build

    steps:
      - uses: actions/setup-java@v4
        name: set up jdk
        with:
          distribution: 'temurin'
          java-version: "22"

      - name: Support longpaths on Windows
        run: git config --global core.longpaths true
          
      - uses: actions/checkout@v4
        name: checkout smallrye-open-api
        with:
          repository: MikeEdgar/smallrye-open-api
          ref: fix-static-doc-leak
          path: smallrye-open-api

      - name: build smallrye-open-api
        run: mvn -B -f smallrye-open-api/pom.xml install -pl extension-jaxrs -am -DskipTests

      - uses: actions/checkout@v4
        name: checkout quarkus
        with:
          repository: MikeEdgar/quarkus
          ref: lock-free-url-stream
          path: quarkus

      - name: build quarkus
        run: |
          cd quarkus
          ./mvnw -B install -pl bom/application,extensions/smallrye-openapi/deployment -am -DskipTests
          cd ..

      - uses: actions/checkout@v4
        name: checkout reproducer
        with:
          path: reproducer

      - name: build reproducer
        run: mvn -B -f reproducer/pom.xml package
